name: AndroidLint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
      - uses: jmatsu/setup-android-problem-matcher@v1
      - run: ./gradlew test
